default:
  site:
    review_period: '13 months'
    spaces:
      -
        space_path: clients/dotnet
        space_name: Client SDK - .NET
    dev_browser_path: /
  verify_paths:
    - index.html
development:
  isDev: true
